; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG247275 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
$SG252017 DB	'%s', 00H
	ORG $+9
$SG247276 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247277 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG247614 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG247615 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247616 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG247953 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG247954 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247955 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG248810 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG248811 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG248812 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG249203 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG249204 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG249205 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG249596 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG249597 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG249598 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_GraphicsPanel@@3Uqt_meta_stringdata_GraphicsPanel_t@@B DD 0ffffffffH ; qt_meta_stringdata_GraphicsPanel
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	000000000000003eH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000034H
	DB	047H
	DB	072H
	DB	061H
	DB	070H
	DB	068H
	DB	069H
	DB	063H
	DB	073H
	DB	050H
	DB	061H
	DB	06eH
	DB	065H
	DB	06cH
	DB	00H
	DB	06fH
	DB	06eH
	DB	050H
	DB	06cH
	DB	061H
	DB	079H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	ORG $+3
	ORG $+8
?qt_meta_data_GraphicsPanel@@3QBIB DD 07H		; qt_meta_data_GraphicsPanel
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	0aH
	DD	02bH
	DD	00H
	ORG $+4
$SG249989 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG249990 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG249991 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG233748 DB	'QOpenGLFunctions', 00H
	ORG $+7
$SG250382 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG250383 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG250384 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG250775 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG250776 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG250777 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG251168 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG251169 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG251170 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG251561 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG251562 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG251563 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG252016 DB	'invalid argument', 00H
	ORG $+15
$SG252018 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG252019 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG252020 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG252021 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+10
$SG252341 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
$SG244300 DB	'C:\Qt\5.11.1\msvc2015_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG244301 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG244302 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	??1VertexData@@QEAA@XZ				; VertexData::~VertexData
PUBLIC	??_EVertexData@@QEAAPEAXI@Z			; VertexData::`vector deleting destructor'
PUBLIC	?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ ; GraphicsPanel::metaObject
PUBLIC	?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z	; GraphicsPanel::qt_metacast
PUBLIC	?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; GraphicsPanel::qt_metacall
PUBLIC	?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; GraphicsPanel::qt_static_metacall
PUBLIC	?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B ; GraphicsPanel::staticMetaObject
EXTRN	??_M@YAXPEAX_K1P6AX0@Z@Z:PROC			; `eh vector destructor iterator'
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	??_V@YAXPEAX_K@Z:PROC				; operator delete[]
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QOpenGLWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QOpenGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onPlayClicked@GraphicsPanel@@QEAAXXZ:PROC	; GraphicsPanel::onPlayClicked
EXTRN	__CxxFrameHandler4:PROC
EXTRN	__imp_?staticMetaObject@QOpenGLWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B DB 030H DUP (?) ; GraphicsPanel::staticMetaObject
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_EVertexData@@QEAAPEAXI@Z DD imagerel $LN6
	DD	imagerel $LN6+158
	DD	imagerel $unwind$??_EVertexData@@QEAAPEAXI@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z DD imagerel $LN8
	DD	imagerel $LN8+136
	DD	imagerel $unwind$?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+72
	DD	imagerel $unwind$?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@GraphicsPanel@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@GraphicsPanel@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0620eH
$unwind$?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??_EVertexData@@QEAAPEAXI@Z DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??_EVertexData@@QEAAPEAXI@Z DB 060H
	DD	imagerel $ip2state$??_EVertexData@@QEAAPEAXI@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_EVertexData@@QEAAPEAXI@Z DD 010d19H
	DD	0420dH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??_EVertexData@@QEAAPEAXI@Z
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'GraphicsPanel::staticMetaObject'', COMDAT
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 79
	mov	rax, QWORD PTR __imp_?staticMetaObject@QOpenGLWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_GraphicsPanel@@3Uqt_meta_stringdata_GraphicsPanel_t@@B
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B+8, rax
; Line 80
	lea	rax, OFFSET FLAT:?qt_meta_data_GraphicsPanel@@3QBIB
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; GraphicsPanel::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'GraphicsPanel::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; GraphicsPanel::qt_static_metacall
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 66
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 67
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 68
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 70
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 71
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onPlayClicked@GraphicsPanel@@QEAAXXZ	; GraphicsPanel::onPlayClicked
$LN6@qt_static_:
$LN4@qt_static_:
; Line 76
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; GraphicsPanel::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; GraphicsPanel::qt_metacall
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 100
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 101
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QOpenGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 102
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 103
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 104
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 105
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 106
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@GraphicsPanel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; GraphicsPanel::qt_static_metacall
$LN5@qt_metacal:
; Line 107
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 108
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 109
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 110
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 111
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 114
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@GraphicsPanel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; GraphicsPanel::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv77 = 32
this$ = 64
_clname$ = 72
?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z PROC		; GraphicsPanel::qt_metacast
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 90
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 91
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 92
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_GraphicsPanel@@3Uqt_meta_stringdata_GraphicsPanel_t@@B+72
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 93
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 94
	lea	rdx, OFFSET FLAT:$SG233748
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN4@qt_metacas
; Line 95
	cmp	QWORD PTR this$[rsp], 0
	je	SHORT $LN6@qt_metacas
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 48					; 00000030H
	mov	QWORD PTR tv77[rsp], rax
	jmp	SHORT $LN7@qt_metacas
$LN6@qt_metacas:
	mov	QWORD PTR tv77[rsp], 0
$LN7@qt_metacas:
	mov	rax, QWORD PTR tv77[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN4@qt_metacas:
; Line 96
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QOpenGLWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 97
	add	rsp, 56					; 00000038H
	ret	0
?qt_metacast@GraphicsPanel@@UEAAPEAXPEBD@Z ENDP		; GraphicsPanel::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ PROC	; GraphicsPanel::metaObject
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 85
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 86
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@GraphicsPanel@@2UQMetaObject@@B ; GraphicsPanel::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 87
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@GraphicsPanel@@UEBAPEBUQMetaObject@@XZ ENDP	; GraphicsPanel::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_EVertexData@@QEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_EVertexData@@QEAAPEAXI@Z PROC			; VertexData::`vector deleting destructor', COMDAT
$LN6:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 2
	test	eax, eax
	je	SHORT $LN2@vector
	lea	r9, OFFSET FLAT:??1VertexData@@QEAA@XZ	; VertexData::~VertexData
	mov	rax, QWORD PTR this$[rsp]
	mov	r8, QWORD PTR [rax-8]
	mov	edx, 32					; 00000020H
	mov	rcx, QWORD PTR this$[rsp]
	call	??_M@YAXPEAX_K1P6AX0@Z@Z
	npad	1
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN3@vector
	mov	rax, QWORD PTR this$[rsp]
	imul	rax, QWORD PTR [rax-8], 32		; 00000020H
	add	rax, 8
	mov	rcx, QWORD PTR this$[rsp]
	sub	rcx, 8
	mov	rdx, rax
	call	??_V@YAXPEAX_K@Z			; operator delete[]
	npad	1
$LN3@vector:
	mov	rax, QWORD PTR this$[rsp]
	sub	rax, 8
	jmp	SHORT $LN1@vector
$LN2@vector:
	mov	rcx, QWORD PTR this$[rsp]
	call	??1VertexData@@QEAA@XZ			; VertexData::~VertexData
	npad	1
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN4@vector
	mov	edx, 32					; 00000020H
	mov	rcx, QWORD PTR this$[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1
$LN4@vector:
	mov	rax, QWORD PTR this$[rsp]
$LN1@vector:
	add	rsp, 40					; 00000028H
	ret	0
??_EVertexData@@QEAAPEAXI@Z ENDP			; VertexData::`vector deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1VertexData@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1VertexData@@QEAA@XZ PROC				; VertexData::~VertexData, COMDAT
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\ShapeCreator.h
; Line 9
	mov	QWORD PTR [rsp+8], rcx
	ret	0
??1VertexData@@QEAA@XZ ENDP				; VertexData::~VertexData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File C:\Qt\5.11.1\msvc2015_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 117
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\jdtho\source\repos\PageantryDesigner\PageantryDesigner\x64\Debug\moc\moc_GraphicsPanel.cpp
; Line 117
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
